---
- name: use role distributed with collection
  hosts: localhost
  connection: ssh
  gather_facts: no

  collections:
  - adalovelace.myfirstcollection

  tasks:
  - name: Example of how to use a collection
    debug:
      msg: "Any new modules, roles or other distributables included in the role would not be usable!"

